name = "ADModelling"
uuid = "afa9199d-b7f6-449d-a519-38a74d95a6ee"
authors = ["Pavanjit Chaggar"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
